/**
 * Original, hand-authored region topology for the geographic Map view —
 * NOT extracted, traced, or derived from any game screenshot, ROM asset,
 * or third-party map image. What's encoded here is factual game-world
 * geography (which route connects which two towns, what kind of terrain
 * it is) — the same kind of fact any strategy guide states in prose
 * ("Route 1 connects Pallet Town to Viridian City") — laid out on an
 * original abstract grid of this app's own design. The visual rendering
 * (RegionMap.tsx) draws its own tile art from these facts; nothing here
 * is copyrighted expression, and nothing it produces is either.
 *
 * `col`/`row` are an approximate topological grid, not real coordinates —
 * they preserve relative position (north/south/east/west of neighbors)
 * well enough to read as "the shape of Kanto," without claiming pixel
 * accuracy to any canonical map.
 */
export type RegionNodeKind = 'town' | 'route' | 'cave' | 'forest' | 'water' | 'landmark';

export interface RegionNode {
  /** Matches the PokeAPI location slug this node represents, so selecting it wires straight into the existing encounter/trainer lookup. */
  locationName: string;
  label: string;
  kind: RegionNodeKind;
  col: number;
  row: number;
  /** locationName of every directly-connected neighbor, for drawing route lines. */
  connections: string[];
}

export const KANTO_LAYOUT: RegionNode[] = [
  { locationName: 'pallet-town', label: 'Pallet Town', kind: 'town', col: 2, row: 11, connections: ['kanto-route-1', 'kanto-route-21'] },
  { locationName: 'kanto-route-1', label: 'Route 1', kind: 'route', col: 2, row: 10, connections: ['pallet-town', 'viridian-city'] },
  { locationName: 'viridian-city', label: 'Viridian City', kind: 'town', col: 2, row: 9, connections: ['kanto-route-1', 'kanto-route-2', 'kanto-route-22'] },
  { locationName: 'kanto-route-2', label: 'Route 2', kind: 'route', col: 2, row: 8, connections: ['viridian-city', 'viridian-forest', 'pewter-city'] },
  { locationName: 'viridian-forest', label: 'Viridian Forest', kind: 'forest', col: 2.6, row: 8, connections: ['kanto-route-2'] },
  { locationName: 'pewter-city', label: 'Pewter City', kind: 'town', col: 2, row: 7, connections: ['kanto-route-2', 'kanto-route-3'] },
  { locationName: 'kanto-route-3', label: 'Route 3', kind: 'route', col: 3, row: 7, connections: ['pewter-city', 'mt-moon'] },
  { locationName: 'mt-moon', label: 'Mt. Moon', kind: 'cave', col: 4, row: 7, connections: ['kanto-route-3', 'kanto-route-4'] },
  { locationName: 'kanto-route-4', label: 'Route 4', kind: 'route', col: 5, row: 7, connections: ['mt-moon', 'cerulean-city'] },
  { locationName: 'cerulean-city', label: 'Cerulean City', kind: 'town', col: 6, row: 7, connections: ['kanto-route-4', 'kanto-route-24', 'kanto-route-5', 'kanto-route-9'] },
  { locationName: 'kanto-route-24', label: 'Route 24', kind: 'route', col: 6, row: 6, connections: ['cerulean-city', 'kanto-route-25'] },
  { locationName: 'kanto-route-25', label: 'Route 25', kind: 'route', col: 6.5, row: 5.5, connections: ['kanto-route-24'] },
  { locationName: 'cerulean-cave', label: 'Cerulean Cave', kind: 'cave', col: 6, row: 5, connections: [] },
  { locationName: 'kanto-route-9', label: 'Route 9', kind: 'route', col: 7, row: 7, connections: ['cerulean-city', 'kanto-route-10'] },
  { locationName: 'kanto-route-10', label: 'Route 10', kind: 'route', col: 7, row: 8, connections: ['kanto-route-9', 'rock-tunnel', 'kanto-power-plant'] },
  { locationName: 'rock-tunnel', label: 'Rock Tunnel', kind: 'cave', col: 7, row: 9, connections: ['kanto-route-10', 'lavender-town'] },
  { locationName: 'kanto-power-plant', label: 'Power Plant', kind: 'landmark', col: 8, row: 8, connections: ['kanto-route-10'] },
  { locationName: 'kanto-route-5', label: 'Route 5', kind: 'route', col: 6, row: 8, connections: ['cerulean-city', 'saffron-city'] },
  { locationName: 'kanto-route-6', label: 'Route 6', kind: 'route', col: 6, row: 10, connections: ['saffron-city', 'vermilion-city'] },
  { locationName: 'vermilion-city', label: 'Vermilion City', kind: 'town', col: 6, row: 11, connections: ['kanto-route-6', 'kanto-route-11', 'ss-anne'] },
  { locationName: 'ss-anne', label: 'S.S. Anne', kind: 'landmark', col: 5, row: 11, connections: ['vermilion-city'] },
  { locationName: 'kanto-route-11', label: 'Route 11', kind: 'route', col: 7, row: 11, connections: ['vermilion-city', 'digletts-cave'] },
  { locationName: 'digletts-cave', label: "Diglett's Cave", kind: 'cave', col: 7, row: 10, connections: ['kanto-route-11'] },
  { locationName: 'saffron-city', label: 'Saffron City', kind: 'town', col: 6, row: 9, connections: ['kanto-route-5', 'kanto-route-6', 'kanto-route-7', 'kanto-route-8'] },
  { locationName: 'kanto-route-7', label: 'Route 7', kind: 'route', col: 5, row: 9, connections: ['saffron-city', 'celadon-city'] },
  { locationName: 'celadon-city', label: 'Celadon City', kind: 'town', col: 4, row: 9, connections: ['kanto-route-7', 'kanto-route-16'] },
  { locationName: 'kanto-route-8', label: 'Route 8', kind: 'route', col: 7, row: 9, connections: ['saffron-city', 'lavender-town'] },
  { locationName: 'lavender-town', label: 'Lavender Town', kind: 'town', col: 8, row: 9, connections: ['kanto-route-8', 'rock-tunnel', 'kanto-route-12', 'pokemon-tower'] },
  { locationName: 'pokemon-tower', label: 'Pokémon Tower', kind: 'landmark', col: 8, row: 8.3, connections: ['lavender-town'] },
  { locationName: 'kanto-route-12', label: 'Route 12', kind: 'route', col: 8, row: 10, connections: ['lavender-town', 'kanto-route-13'] },
  { locationName: 'kanto-route-13', label: 'Route 13', kind: 'route', col: 8, row: 11, connections: ['kanto-route-12', 'kanto-route-14'] },
  { locationName: 'kanto-route-14', label: 'Route 14', kind: 'route', col: 7, row: 11.5, connections: ['kanto-route-13', 'kanto-route-15'] },
  { locationName: 'kanto-route-15', label: 'Route 15', kind: 'route', col: 6, row: 12, connections: ['kanto-route-14', 'fuchsia-city'] },
  { locationName: 'fuchsia-city', label: 'Fuchsia City', kind: 'town', col: 5, row: 12, connections: ['kanto-route-15', 'kanto-route-18', 'kanto-route-19', 'kanto-safari-zone'] },
  { locationName: 'kanto-safari-zone', label: 'Safari Zone', kind: 'landmark', col: 5, row: 13, connections: ['fuchsia-city'] },
  { locationName: 'kanto-route-16', label: 'Route 16', kind: 'route', col: 4, row: 10, connections: ['celadon-city', 'kanto-route-17'] },
  { locationName: 'kanto-route-17', label: 'Route 17', kind: 'route', col: 4, row: 11, connections: ['kanto-route-16', 'kanto-route-18'] },
  { locationName: 'kanto-route-18', label: 'Route 18', kind: 'route', col: 4, row: 12, connections: ['kanto-route-17', 'fuchsia-city'] },
  { locationName: 'kanto-route-19', label: 'Route 19', kind: 'water', col: 5, row: 13, connections: ['fuchsia-city', 'kanto-sea-route-20'] },
  { locationName: 'kanto-sea-route-20', label: 'Route 20', kind: 'water', col: 4, row: 13, connections: ['kanto-route-19', 'seafoam-islands', 'cinnabar-island'] },
  { locationName: 'seafoam-islands', label: 'Seafoam Islands', kind: 'cave', col: 4, row: 12.3, connections: ['kanto-sea-route-20'] },
  { locationName: 'cinnabar-island', label: 'Cinnabar Island', kind: 'town', col: 3, row: 13, connections: ['kanto-sea-route-20', 'kanto-route-21', 'pokemon-mansion'] },
  { locationName: 'pokemon-mansion', label: 'Pokémon Mansion', kind: 'landmark', col: 3, row: 13.7, connections: ['cinnabar-island'] },
  { locationName: 'kanto-route-21', label: 'Route 21', kind: 'water', col: 2.5, row: 12, connections: ['cinnabar-island', 'pallet-town'] },
  { locationName: 'kanto-route-22', label: 'Route 22', kind: 'route', col: 1, row: 9, connections: ['viridian-city', 'kanto-route-23'] },
  { locationName: 'kanto-route-23', label: 'Route 23', kind: 'route', col: 1, row: 8, connections: ['kanto-route-22', 'kanto-victory-road-1'] },
  { locationName: 'kanto-victory-road-1', label: 'Victory Road', kind: 'cave', col: 1, row: 7, connections: ['kanto-route-23', 'indigo-plateau'] },
  { locationName: 'indigo-plateau', label: 'Indigo Plateau', kind: 'landmark', col: 1, row: 6, connections: ['kanto-victory-road-1'] },
];

export const JOHTO_LAYOUT: RegionNode[] = [
  { locationName: 'new-bark-town', label: 'New Bark Town', kind: 'town', col: 10, row: 10, connections: ['johto-route-29', 'johto-route-27'] },
  { locationName: 'johto-route-29', label: 'Route 29', kind: 'route', col: 9, row: 10, connections: ['new-bark-town', 'cherrygrove-city'] },
  { locationName: 'cherrygrove-city', label: 'Cherrygrove City', kind: 'town', col: 8, row: 10, connections: ['johto-route-29', 'johto-route-30'] },
  { locationName: 'johto-route-30', label: 'Route 30', kind: 'route', col: 8, row: 9, connections: ['cherrygrove-city', 'violet-city', 'johto-route-46'] },
  { locationName: 'johto-route-46', label: 'Route 46', kind: 'route', col: 8.6, row: 9, connections: ['johto-route-30', 'johto-route-45'] },
  { locationName: 'violet-city', label: 'Violet City', kind: 'town', col: 8, row: 8, connections: ['johto-route-30', 'sprout-tower', 'johto-route-31'] },
  { locationName: 'sprout-tower', label: 'Sprout Tower', kind: 'landmark', col: 7.3, row: 8, connections: ['violet-city'] },
  { locationName: 'johto-route-31', label: 'Route 31', kind: 'route', col: 8, row: 7, connections: ['violet-city', 'dark-cave', 'union-cave'] },
  { locationName: 'dark-cave', label: 'Dark Cave', kind: 'cave', col: 8.6, row: 7, connections: ['johto-route-31', 'johto-route-45'] },
  { locationName: 'union-cave', label: 'Union Cave', kind: 'cave', col: 8, row: 6, connections: ['johto-route-31', 'ruins-of-alph', 'johto-route-32'] },
  { locationName: 'ruins-of-alph', label: 'Ruins of Alph', kind: 'landmark', col: 7.3, row: 6, connections: ['union-cave'] },
  { locationName: 'johto-route-32', label: 'Route 32', kind: 'route', col: 7, row: 5.3, connections: ['union-cave', 'johto-route-33'] },
  { locationName: 'johto-route-33', label: 'Route 33', kind: 'route', col: 6, row: 5.3, connections: ['johto-route-32', 'azalea-town'] },
  { locationName: 'azalea-town', label: 'Azalea Town', kind: 'town', col: 6, row: 4.6, connections: ['johto-route-33', 'slowpoke-well', 'ilex-forest'] },
  { locationName: 'slowpoke-well', label: 'Slowpoke Well', kind: 'cave', col: 5.3, row: 4.6, connections: ['azalea-town'] },
  { locationName: 'ilex-forest', label: 'Ilex Forest', kind: 'forest', col: 6, row: 3.8, connections: ['azalea-town', 'johto-route-34'] },
  { locationName: 'johto-route-34', label: 'Route 34', kind: 'route', col: 6, row: 3, connections: ['ilex-forest', 'goldenrod-city'] },
  { locationName: 'goldenrod-city', label: 'Goldenrod City', kind: 'town', col: 6, row: 2.2, connections: ['johto-route-34', 'goldenrod-tunnel', 'radio-tower', 'pokeathlon-dome', 'johto-route-35'] },
  { locationName: 'goldenrod-tunnel', label: 'Goldenrod Tunnel', kind: 'cave', col: 6.6, row: 2.2, connections: ['goldenrod-city'] },
  { locationName: 'radio-tower', label: 'Radio Tower', kind: 'landmark', col: 5.4, row: 2.2, connections: ['goldenrod-city'] },
  { locationName: 'pokeathlon-dome', label: 'Pokéathlon Dome', kind: 'landmark', col: 6.6, row: 1.6, connections: ['goldenrod-city'] },
  { locationName: 'johto-route-35', label: 'Route 35', kind: 'route', col: 6, row: 1.4, connections: ['goldenrod-city', 'national-park'] },
  { locationName: 'national-park', label: 'National Park', kind: 'route', col: 6, row: 0.6, connections: ['johto-route-35', 'johto-route-36'] },
  { locationName: 'johto-route-36', label: 'Route 36', kind: 'route', col: 5, row: 0.6, connections: ['national-park', 'johto-route-37'] },
  { locationName: 'johto-route-37', label: 'Route 37', kind: 'route', col: 4, row: 0.6, connections: ['johto-route-36', 'ecruteak-city'] },
  { locationName: 'ecruteak-city', label: 'Ecruteak City', kind: 'town', col: 3, row: 0.6, connections: ['johto-route-37', 'burned-tower', 'bell-tower', 'johto-route-38', 'johto-route-42'] },
  { locationName: 'burned-tower', label: 'Burned Tower', kind: 'landmark', col: 2.3, row: 0.6, connections: ['ecruteak-city'] },
  { locationName: 'bell-tower', label: 'Bell Tower', kind: 'landmark', col: 3, row: -0.2, connections: ['ecruteak-city'] },
  { locationName: 'johto-route-38', label: 'Route 38', kind: 'route', col: 2, row: 0.6, connections: ['ecruteak-city', 'johto-route-39'] },
  { locationName: 'johto-route-39', label: 'Route 39', kind: 'route', col: 1, row: 0.6, connections: ['johto-route-38', 'olivine-city'] },
  { locationName: 'olivine-city', label: 'Olivine City', kind: 'town', col: 0, row: 0.6, connections: ['johto-route-39', 'johto-lighthouse', 'ss-aqua', 'johto-sea-route-40'] },
  { locationName: 'johto-lighthouse', label: 'Olivine Lighthouse', kind: 'landmark', col: -0.6, row: 0.1, connections: ['olivine-city'] },
  { locationName: 'ss-aqua', label: 'S.S. Aqua', kind: 'landmark', col: -0.6, row: 1.1, connections: ['olivine-city'] },
  { locationName: 'johto-sea-route-40', label: 'Route 40', kind: 'water', col: 0, row: 1.6, connections: ['olivine-city', 'whirl-islands', 'cianwood-city'] },
  { locationName: 'whirl-islands', label: 'Whirl Islands', kind: 'cave', col: 0.6, row: 2.1, connections: ['johto-sea-route-40'] },
  { locationName: 'cianwood-city', label: 'Cianwood City', kind: 'town', col: 0, row: 2.6, connections: ['johto-sea-route-40', 'johto-sea-route-41'] },
  { locationName: 'johto-sea-route-41', label: 'Route 41', kind: 'water', col: 0.6, row: 3.1, connections: ['cianwood-city'] },
  { locationName: 'johto-route-42', label: 'Route 42', kind: 'route', col: 3, row: 1.4, connections: ['ecruteak-city', 'mt-mortar'] },
  { locationName: 'mt-mortar', label: 'Mt. Mortar', kind: 'cave', col: 3, row: 2.2, connections: ['johto-route-42', 'mahogany-town'] },
  { locationName: 'mahogany-town', label: 'Mahogany Town', kind: 'town', col: 3, row: 3, connections: ['mt-mortar', 'team-rocket-hq', 'johto-route-43', 'johto-route-44'] },
  { locationName: 'team-rocket-hq', label: 'Team Rocket HQ', kind: 'landmark', col: 3.7, row: 3, connections: ['mahogany-town'] },
  { locationName: 'johto-route-43', label: 'Route 43', kind: 'route', col: 3.7, row: 3.7, connections: ['mahogany-town', 'lake-of-rage'] },
  { locationName: 'lake-of-rage', label: 'Lake of Rage', kind: 'water', col: 4.3, row: 3.7, connections: ['johto-route-43'] },
  { locationName: 'johto-route-44', label: 'Route 44', kind: 'route', col: 2.3, row: 3.7, connections: ['mahogany-town', 'ice-path'] },
  { locationName: 'ice-path', label: 'Ice Path', kind: 'cave', col: 2.3, row: 4.5, connections: ['johto-route-44', 'blackthorn-city'] },
  { locationName: 'blackthorn-city', label: 'Blackthorn City', kind: 'town', col: 2.3, row: 5.3, connections: ['ice-path', 'dragons-den', 'johto-route-45'] },
  { locationName: 'dragons-den', label: "Dragon's Den", kind: 'water', col: 1.6, row: 5.3, connections: ['blackthorn-city'] },
  { locationName: 'johto-route-45', label: 'Route 45', kind: 'route', col: 2.3, row: 6, connections: ['blackthorn-city', 'johto-route-46', 'dark-cave'] },
  { locationName: 'johto-route-27', label: 'Route 27', kind: 'route', col: 10, row: 9, connections: ['new-bark-town', 'johto-route-26'] },
  { locationName: 'johto-route-26', label: 'Route 26', kind: 'route', col: 10, row: 8, connections: ['johto-route-27', 'johto-route-28'] },
  { locationName: 'johto-route-28', label: 'Route 28', kind: 'route', col: 10, row: 7, connections: ['johto-route-26', 'mt-silver'] },
  { locationName: 'mt-silver', label: 'Mt. Silver', kind: 'cave', col: 10, row: 6, connections: ['johto-route-28'] },
];

export const HOENN_LAYOUT: RegionNode[] = [
  { locationName: 'littleroot-town', label: 'Littleroot Town', kind: 'town', col: 3, row: 12, connections: ['hoenn-route-101'] },
  { locationName: 'hoenn-route-101', label: 'Route 101', kind: 'route', col: 3, row: 11, connections: ['littleroot-town', 'oldale-town'] },
  { locationName: 'oldale-town', label: 'Oldale Town', kind: 'town', col: 3, row: 10, connections: ['hoenn-route-101', 'hoenn-route-102', 'hoenn-route-103'] },
  { locationName: 'hoenn-route-103', label: 'Route 103', kind: 'route', col: 3.6, row: 10, connections: ['oldale-town'] },
  { locationName: 'hoenn-route-102', label: 'Route 102', kind: 'route', col: 2, row: 10, connections: ['oldale-town', 'petalburg-city'] },
  { locationName: 'petalburg-city', label: 'Petalburg City', kind: 'town', col: 1, row: 10, connections: ['hoenn-route-102', 'hoenn-route-104', 'hoenn-route-105'] },
  { locationName: 'hoenn-route-104', label: 'Route 104', kind: 'route', col: 1, row: 9, connections: ['petalburg-city', 'petalburg-woods', 'rustboro-city'] },
  { locationName: 'petalburg-woods', label: 'Petalburg Woods', kind: 'forest', col: 0.4, row: 9, connections: ['hoenn-route-104'] },
  { locationName: 'rustboro-city', label: 'Rustboro City', kind: 'town', col: 1, row: 8, connections: ['hoenn-route-104', 'hoenn-route-116', 'hoenn-route-115'] },
  { locationName: 'hoenn-route-116', label: 'Route 116', kind: 'route', col: 1, row: 7, connections: ['rustboro-city', 'rusturf-tunnel', 'verdanturf-town'] },
  { locationName: 'rusturf-tunnel', label: 'Rusturf Tunnel', kind: 'cave', col: 0.4, row: 7, connections: ['hoenn-route-116'] },
  { locationName: 'verdanturf-town', label: 'Verdanturf Town', kind: 'town', col: 1, row: 6, connections: ['hoenn-route-116', 'hoenn-route-117'] },
  { locationName: 'hoenn-route-117', label: 'Route 117', kind: 'route', col: 1.6, row: 5.5, connections: ['verdanturf-town', 'mauville-city'] },
  { locationName: 'mauville-city', label: 'Mauville City', kind: 'town', col: 2, row: 5, connections: ['hoenn-route-117', 'hoenn-route-118', 'hoenn-route-111', 'hoenn-route-110', 'new-mauville'] },
  { locationName: 'new-mauville', label: 'New Mauville', kind: 'landmark', col: 2.6, row: 5, connections: ['mauville-city'] },
  { locationName: 'hoenn-route-118', label: 'Route 118', kind: 'route', col: 3, row: 5, connections: ['mauville-city', 'hoenn-route-119'] },
  { locationName: 'hoenn-route-119', label: 'Route 119', kind: 'route', col: 3.6, row: 4.3, connections: ['hoenn-route-118', 'fortree-city'] },
  { locationName: 'fortree-city', label: 'Fortree City', kind: 'town', col: 3.6, row: 3.5, connections: ['hoenn-route-119', 'hoenn-route-120'] },
  { locationName: 'hoenn-route-120', label: 'Route 120', kind: 'route', col: 3, row: 3, connections: ['fortree-city', 'hoenn-route-121'] },
  { locationName: 'hoenn-route-121', label: 'Route 121', kind: 'route', col: 2.3, row: 2.6, connections: ['hoenn-route-120', 'lilycove-city', 'hoenn-safari-zone'] },
  { locationName: 'hoenn-safari-zone', label: 'Safari Zone', kind: 'landmark', col: 1.7, row: 2.3, connections: ['hoenn-route-121'] },
  { locationName: 'hoenn-route-111', label: 'Route 111', kind: 'route', col: 2, row: 4.3, connections: ['mauville-city', 'hoenn-route-112'] },
  { locationName: 'hoenn-route-112', label: 'Route 112', kind: 'route', col: 2, row: 3.6, connections: ['hoenn-route-111', 'mt-chimney', 'fiery-path'] },
  { locationName: 'mt-chimney', label: 'Mt. Chimney', kind: 'landmark', col: 2, row: 3, connections: ['hoenn-route-112'] },
  { locationName: 'fiery-path', label: 'Fiery Path', kind: 'cave', col: 1.4, row: 3.6, connections: ['hoenn-route-112', 'lavaridge-town'] },
  { locationName: 'lavaridge-town', label: 'Lavaridge Town', kind: 'town', col: 1.4, row: 3, connections: ['fiery-path', 'hoenn-route-113'] },
  { locationName: 'hoenn-route-113', label: 'Route 113', kind: 'route', col: 0.7, row: 3, connections: ['lavaridge-town', 'fallarbor-town'] },
  { locationName: 'fallarbor-town', label: 'Fallarbor Town', kind: 'town', col: 0, row: 3, connections: ['hoenn-route-113', 'hoenn-route-114'] },
  { locationName: 'hoenn-route-114', label: 'Route 114', kind: 'route', col: 0, row: 4, connections: ['fallarbor-town', 'meteor-falls', 'hoenn-route-115'] },
  { locationName: 'meteor-falls', label: 'Meteor Falls', kind: 'cave', col: -0.6, row: 4, connections: ['hoenn-route-114'] },
  { locationName: 'hoenn-route-115', label: 'Route 115', kind: 'route', col: 0, row: 5, connections: ['hoenn-route-114', 'rustboro-city'] },
  { locationName: 'hoenn-route-105', label: 'Route 105', kind: 'water', col: 1, row: 9.7, connections: ['petalburg-city', 'dewford-town'] },
  { locationName: 'dewford-town', label: 'Dewford Town', kind: 'town', col: 1, row: 11.5, connections: ['hoenn-route-105', 'hoenn-route-106', 'hoenn-route-107'] },
  { locationName: 'hoenn-route-106', label: 'Route 106', kind: 'water', col: 0.4, row: 11.5, connections: ['dewford-town', 'granite-cave'] },
  { locationName: 'granite-cave', label: 'Granite Cave', kind: 'cave', col: -0.2, row: 11.5, connections: ['hoenn-route-106'] },
  { locationName: 'hoenn-route-107', label: 'Route 107', kind: 'water', col: 1.6, row: 12, connections: ['dewford-town'] },
  { locationName: 'hoenn-route-108', label: 'Route 108', kind: 'water', col: 2, row: 11.5, connections: ['dewford-town', 'hoenn-route-109', 'abandoned-ship'] },
  { locationName: 'abandoned-ship', label: 'Abandoned Ship', kind: 'landmark', col: 2.6, row: 12, connections: ['hoenn-route-108'] },
  { locationName: 'hoenn-route-109', label: 'Route 109', kind: 'water', col: 2.6, row: 11, connections: ['hoenn-route-108', 'slateport-city'] },
  { locationName: 'slateport-city', label: 'Slateport City', kind: 'town', col: 3, row: 10.5, connections: ['hoenn-route-109', 'hoenn-route-110', 'hoenn-route-134'] },
  { locationName: 'hoenn-route-110', label: 'Route 110', kind: 'route', col: 3, row: 9.5, connections: ['slateport-city', 'mauville-city'] },
  { locationName: 'hoenn-route-134', label: 'Route 134', kind: 'water', col: 3.6, row: 10.5, connections: ['slateport-city'] },
  { locationName: 'lilycove-city', label: 'Lilycove City', kind: 'town', col: 2, row: 2, connections: ['hoenn-route-121', 'hoenn-route-122', 'hoenn-route-124'] },
  { locationName: 'hoenn-route-122', label: 'Route 122', kind: 'water', col: 1.4, row: 1.6, connections: ['lilycove-city', 'mt-pyre'] },
  { locationName: 'mt-pyre', label: 'Mt. Pyre', kind: 'landmark', col: 0.8, row: 1.6, connections: ['hoenn-route-122'] },
  { locationName: 'hoenn-route-124', label: 'Route 124', kind: 'water', col: 2, row: 1, connections: ['lilycove-city', 'mossdeep-city'] },
  { locationName: 'mossdeep-city', label: 'Mossdeep City', kind: 'town', col: 2, row: 0.2, connections: ['hoenn-route-124', 'hoenn-route-125', 'mossdeep-space-center'] },
  { locationName: 'mossdeep-space-center', label: 'Space Center', kind: 'landmark', col: 2.6, row: 0.2, connections: ['mossdeep-city'] },
  { locationName: 'hoenn-route-125', label: 'Route 125', kind: 'water', col: 1.4, row: 0.2, connections: ['mossdeep-city', 'shoal-cave'] },
  { locationName: 'shoal-cave', label: 'Shoal Cave', kind: 'cave', col: 0.8, row: 0.2, connections: ['hoenn-route-125'] },
  { locationName: 'hoenn-route-126', label: 'Route 126', kind: 'water', col: 1.4, row: -0.5, connections: ['mossdeep-city', 'sootopolis-city'] },
  { locationName: 'sootopolis-city', label: 'Sootopolis City', kind: 'town', col: 1, row: -1.2, connections: ['hoenn-route-126', 'hoenn-route-127', 'cave-of-origin', 'seafloor-cavern'] },
  { locationName: 'cave-of-origin', label: 'Cave of Origin', kind: 'cave', col: 0.4, row: -1.2, connections: ['sootopolis-city'] },
  { locationName: 'seafloor-cavern', label: 'Seafloor Cavern', kind: 'cave', col: 0.4, row: -0.6, connections: ['sootopolis-city'] },
  { locationName: 'hoenn-route-127', label: 'Route 127', kind: 'water', col: 1.7, row: -1.2, connections: ['sootopolis-city', 'hoenn-route-128'] },
  { locationName: 'hoenn-route-128', label: 'Route 128', kind: 'water', col: 2.3, row: -1.2, connections: ['hoenn-route-127', 'hoenn-victory-road'] },
  { locationName: 'hoenn-victory-road', label: 'Victory Road', kind: 'cave', col: 2.9, row: -1.2, connections: ['hoenn-route-128', 'ever-grande-city'] },
  { locationName: 'ever-grande-city', label: 'Ever Grande City', kind: 'town', col: 3.5, row: -1.2, connections: ['hoenn-victory-road', 'hoenn-pokemon-league'] },
  { locationName: 'hoenn-pokemon-league', label: 'Pokémon League', kind: 'landmark', col: 4.1, row: -1.2, connections: ['ever-grande-city'] },
  { locationName: 'hoenn-route-129', label: 'Route 129', kind: 'water', col: 1, row: -2, connections: ['sootopolis-city', 'hoenn-route-130', 'sky-pillar'] },
  { locationName: 'sky-pillar', label: 'Sky Pillar', kind: 'landmark', col: 0.4, row: -2, connections: ['hoenn-route-129'] },
  { locationName: 'hoenn-route-130', label: 'Route 130', kind: 'water', col: 0.4, row: -2.6, connections: ['hoenn-route-129', 'pacifidlog-town'] },
  { locationName: 'pacifidlog-town', label: 'Pacifidlog Town', kind: 'town', col: -0.2, row: -2.6, connections: ['hoenn-route-130', 'hoenn-route-131'] },
  { locationName: 'hoenn-route-131', label: 'Route 131', kind: 'water', col: -0.8, row: -2.6, connections: ['pacifidlog-town'] },
];

export const SINNOH_LAYOUT: RegionNode[] = [
  { locationName: 'twinleaf-town', label: 'Twinleaf Town', kind: 'town', col: 2, row: 12, connections: ['sinnoh-route-201'] },
  { locationName: 'sinnoh-route-201', label: 'Route 201', kind: 'route', col: 2, row: 11, connections: ['twinleaf-town', 'sandgem-town'] },
  { locationName: 'sandgem-town', label: 'Sandgem Town', kind: 'town', col: 2, row: 10, connections: ['sinnoh-route-201', 'sinnoh-route-202', 'lake-verity'] },
  { locationName: 'lake-verity', label: 'Lake Verity', kind: 'water', col: 1.4, row: 10, connections: ['sandgem-town'] },
  { locationName: 'sinnoh-route-202', label: 'Route 202', kind: 'route', col: 2, row: 9, connections: ['sandgem-town', 'jubilife-city'] },
  { locationName: 'jubilife-city', label: 'Jubilife City', kind: 'town', col: 2, row: 8, connections: ['sinnoh-route-202', 'sinnoh-route-203', 'sinnoh-route-204', 'sinnoh-route-218'] },
  { locationName: 'sinnoh-route-203', label: 'Route 203', kind: 'route', col: 2.6, row: 7.6, connections: ['jubilife-city', 'oreburgh-gate'] },
  { locationName: 'oreburgh-gate', label: 'Oreburgh Gate', kind: 'cave', col: 3.2, row: 7.3, connections: ['sinnoh-route-203', 'oreburgh-city'] },
  { locationName: 'oreburgh-city', label: 'Oreburgh City', kind: 'town', col: 3.8, row: 7, connections: ['oreburgh-gate', 'oreburgh-mine', 'sinnoh-route-207'] },
  { locationName: 'oreburgh-mine', label: 'Oreburgh Mine', kind: 'cave', col: 4.4, row: 7, connections: ['oreburgh-city'] },
  { locationName: 'sinnoh-route-207', label: 'Route 207', kind: 'route', col: 3.8, row: 6.2, connections: ['oreburgh-city', 'mt-coronet'] },
  { locationName: 'sinnoh-route-204', label: 'Route 204', kind: 'route', col: 1.4, row: 7.6, connections: ['jubilife-city', 'ravaged-path', 'floaroma-town'] },
  { locationName: 'ravaged-path', label: 'Ravaged Path', kind: 'cave', col: 1, row: 7.3, connections: ['sinnoh-route-204'] },
  { locationName: 'floaroma-town', label: 'Floaroma Town', kind: 'town', col: 1, row: 7, connections: ['sinnoh-route-204', 'sinnoh-route-205', 'floaroma-meadow', 'valley-windworks'] },
  { locationName: 'floaroma-meadow', label: 'Floaroma Meadow', kind: 'landmark', col: 0.4, row: 7, connections: ['floaroma-town'] },
  { locationName: 'valley-windworks', label: 'Valley Windworks', kind: 'landmark', col: 1, row: 6.4, connections: ['floaroma-town'] },
  { locationName: 'sinnoh-route-205', label: 'Route 205', kind: 'route', col: 1.6, row: 6, connections: ['floaroma-town', 'eterna-forest'] },
  { locationName: 'eterna-forest', label: 'Eterna Forest', kind: 'forest', col: 1.6, row: 5.3, connections: ['sinnoh-route-205', 'eterna-city'] },
  { locationName: 'eterna-city', label: 'Eterna City', kind: 'town', col: 1.6, row: 4.6, connections: ['eterna-forest', 'sinnoh-route-206', 'sinnoh-route-211', 'galactic-hq'] },
  { locationName: 'galactic-hq', label: 'Galactic HQ', kind: 'landmark', col: 1, row: 4.6, connections: ['eterna-city'] },
  { locationName: 'sinnoh-route-206', label: 'Route 206', kind: 'route', col: 2.4, row: 4.3, connections: ['eterna-city', 'sinnoh-route-207'] },
  { locationName: 'sinnoh-route-211', label: 'Route 211', kind: 'route', col: 1.6, row: 3.8, connections: ['eterna-city', 'celestic-town', 'mt-coronet'] },
  { locationName: 'celestic-town', label: 'Celestic Town', kind: 'town', col: 1, row: 3.5, connections: ['sinnoh-route-211'] },
  { locationName: 'mt-coronet', label: 'Mt. Coronet', kind: 'cave', col: 2.4, row: 3.5, connections: ['sinnoh-route-207', 'sinnoh-route-211', 'sinnoh-route-208', 'sinnoh-route-216', 'spear-pillar'] },
  { locationName: 'spear-pillar', label: 'Spear Pillar', kind: 'landmark', col: 2.4, row: 2.8, connections: ['mt-coronet'] },
  { locationName: 'sinnoh-route-208', label: 'Route 208', kind: 'route', col: 3.2, row: 3.8, connections: ['mt-coronet', 'hearthome-city'] },
  { locationName: 'hearthome-city', label: 'Hearthome City', kind: 'town', col: 3.8, row: 4.3, connections: ['sinnoh-route-208', 'sinnoh-route-209', 'sinnoh-route-210', 'amity-square'] },
  { locationName: 'amity-square', label: 'Amity Square', kind: 'landmark', col: 4.4, row: 4.3, connections: ['hearthome-city'] },
  { locationName: 'sinnoh-route-209', label: 'Route 209', kind: 'route', col: 4.4, row: 5, connections: ['hearthome-city', 'solaceon-town'] },
  { locationName: 'solaceon-town', label: 'Solaceon Town', kind: 'town', col: 5, row: 5.5, connections: ['sinnoh-route-209', 'sinnoh-route-210', 'solaceon-ruins'] },
  { locationName: 'solaceon-ruins', label: 'Solaceon Ruins', kind: 'landmark', col: 5.6, row: 5.5, connections: ['solaceon-town'] },
  { locationName: 'sinnoh-route-210', label: 'Route 210', kind: 'route', col: 4.4, row: 6, connections: ['solaceon-town', 'veilstone-city'] },
  { locationName: 'veilstone-city', label: 'Veilstone City', kind: 'town', col: 4.4, row: 6.7, connections: ['sinnoh-route-210', 'sinnoh-route-214', 'sinnoh-route-215'] },
  { locationName: 'sinnoh-route-214', label: 'Route 214', kind: 'route', col: 5, row: 7.3, connections: ['veilstone-city', 'sinnoh-route-213'] },
  { locationName: 'sinnoh-route-215', label: 'Route 215', kind: 'route', col: 4.4, row: 7.4, connections: ['veilstone-city', 'sinnoh-route-213'] },
  { locationName: 'sinnoh-route-213', label: 'Route 213', kind: 'route', col: 4.4, row: 8.1, connections: ['sinnoh-route-214', 'sinnoh-route-215', 'pastoria-city'] },
  { locationName: 'pastoria-city', label: 'Pastoria City', kind: 'town', col: 4.4, row: 8.8, connections: ['sinnoh-route-213', 'sinnoh-route-212', 'great-marsh'] },
  { locationName: 'great-marsh', label: 'Great Marsh', kind: 'landmark', col: 5, row: 8.8, connections: ['pastoria-city'] },
  { locationName: 'sinnoh-route-212', label: 'Route 212', kind: 'route', col: 3.6, row: 8.4, connections: ['pastoria-city', 'hearthome-city'] },
  { locationName: 'sinnoh-route-216', label: 'Route 216', kind: 'route', col: 3, row: 2.8, connections: ['mt-coronet', 'sinnoh-route-217'] },
  { locationName: 'sinnoh-route-217', label: 'Route 217', kind: 'route', col: 3, row: 2, connections: ['sinnoh-route-216', 'snowpoint-city'] },
  { locationName: 'snowpoint-city', label: 'Snowpoint City', kind: 'town', col: 3, row: 1.3, connections: ['sinnoh-route-217', 'snowpoint-temple', 'lake-acuity'] },
  { locationName: 'snowpoint-temple', label: 'Snowpoint Temple', kind: 'landmark', col: 3.6, row: 1.3, connections: ['snowpoint-city'] },
  { locationName: 'lake-acuity', label: 'Lake Acuity', kind: 'water', col: 2.4, row: 1.3, connections: ['snowpoint-city'] },
  { locationName: 'sinnoh-route-218', label: 'Route 218', kind: 'route', col: 1.4, row: 8.4, connections: ['jubilife-city', 'canalave-city'] },
  { locationName: 'canalave-city', label: 'Canalave City', kind: 'town', col: 0.8, row: 8.4, connections: ['sinnoh-route-218', 'iron-island'] },
  { locationName: 'iron-island', label: 'Iron Island', kind: 'cave', col: 0.2, row: 8.4, connections: ['canalave-city'] },
  { locationName: 'lake-valor', label: 'Lake Valor', kind: 'water', col: 3, row: 8.8, connections: ['sinnoh-route-212'] },
  { locationName: 'resort-area', label: 'Resort Area', kind: 'landmark', col: 5, row: 9.6, connections: ['pastoria-city', 'fight-area'] },
  { locationName: 'fight-area', label: 'Fight Area', kind: 'landmark', col: 5.6, row: 9.6, connections: ['resort-area', 'survival-area'] },
  { locationName: 'survival-area', label: 'Survival Area', kind: 'landmark', col: 6.2, row: 9.6, connections: ['fight-area', 'stark-mountain'] },
  { locationName: 'stark-mountain', label: 'Stark Mountain', kind: 'cave', col: 6.2, row: 10.3, connections: ['survival-area'] },
  { locationName: 'sunyshore-city', label: 'Sunyshore City', kind: 'town', col: 5.6, row: 7.3, connections: ['sinnoh-victory-road'] },
  { locationName: 'sinnoh-victory-road', label: 'Victory Road', kind: 'cave', col: 5.6, row: 6.5, connections: ['sunyshore-city', 'sinnoh-pokemon-league'] },
  { locationName: 'sinnoh-pokemon-league', label: 'Pokémon League', kind: 'landmark', col: 5.6, row: 5.8, connections: ['sinnoh-victory-road'] },
];

export const REGION_LAYOUTS: Record<string, RegionNode[]> = {
  kanto: KANTO_LAYOUT,
  johto: JOHTO_LAYOUT,
  hoenn: HOENN_LAYOUT,
  sinnoh: SINNOH_LAYOUT,
};
